code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension adrianwilczynski.terminal-commands
code --install-extension akamud.vscode-theme-onedark
code --install-extension aksharpatel47.vscode-flutter-helper
code --install-extension alefragnani.Bookmarks
code --install-extension alexisvt.flutter-snippets
code --install-extension AndrijaRubelj.flutterpubopen
code --install-extension Ascenio.dart-union-class
code --install-extension bbenoist.shell
code --install-extension BendixMa.dart-data-class-generator
code --install-extension BrunoLM.export-index
code --install-extension castwide.solargraph
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension circlecodesolution.ccs-flutter-color
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Compulim.vscode-clock
code --install-extension cschlosser.doxdocgen
code --install-extension cssho.vscode-svgviewer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension davidwoo.flutter-auto-import
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension FelixAngelov.bloc
code --install-extension Flutterando.flutter-mobx
code --install-extension funkyremi.vscode-google-translate
code --install-extension fwcd.kotlin
code --install-extension gaetschwartz.build-runner
code --install-extension GitHub.github-vscode-theme
code --install-extension gmlewis-vscode.flutter-stylizer
code --install-extension Gruntfuggly.todo-tree
code --install-extension HossamMourad.vscode-get-color-name
code --install-extension jasonnutter.search-node-modules
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension jerrygoyal.shortcut-menu-bar
code --install-extension jnbt.vscode-rufo
code --install-extension Kelvin.vscode-sshfs
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension kortina.run-in-terminal
code --install-extension leizongmin.node-module-intellisense
code --install-extension luanpotter.dart-import
code --install-extension marcelovelasquez.flutter-tree
code --install-extension matthiaskuech.run-script
code --install-extension mbessey.vscode-rufo
code --install-extension miquelddg.dart-barrel-file-generator
code --install-extension mohsen1.prettify-json
code --install-extension ms-dotnettools.csharp
code --install-extension Nash.awesome-flutter-snippets
code --install-extension natqe.reload
code --install-extension nolancorcoran.dart-exports
code --install-extension oderwat.indent-rainbow
code --install-extension orestesgaolin.dart-export-index
code --install-extension oscarcs.dart-syntax-highlighting-only
code --install-extension panuavakul.mvvm-flutter-widget
code --install-extension piyushvscode.nodejs-snippets
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-xml
code --install-extension remcoros.startanyshell
code --install-extension SimonSiefke.svg-preview
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Swaspy.youtube
code --install-extension timonwong.shellcheck
code --install-extension tomzx.run-me
code --install-extension traBpUkciP.vscode-npm-scripts
code --install-extension tygooch.autoclose-find
code --install-extension Tyriar.shell-launcher
code --install-extension TzachOvadia.todo-list
code --install-extension vikas.code-navigation
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vladmrnv.expresssnippet
code --install-extension volynetsserhii.get-color-name
code --install-extension vscode-snippet.snippet
code --install-extension waderyan.nodejs-extension-pack
code --install-extension wayou.vscode-todo-highlight
code --install-extension wingrunr21.vscode-ruby
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yamajyn.commandlist
code --install-extension YashPaneliya.fast-dart
code --install-extension yt1997kt.flutter-bloc
code --install-extension ZainChen.json
code --install-extension zhuangtongfa.material-theme